import type { IIconPickerOption } from "@/shared/form";

export const INSTRUMENT_ICON_OPTIONS: IIconPickerOption[] = [
  { value: "ph:guitar", label: "Guitarra" },
  { value: "ph:piano-keys", label: "Piano / Teclado" },
  { value: "ph:microphone", label: "Micrófono" },
  { value: "ph:microphone-stage", label: "Micrófono de escenario" },
  { value: "ph:metronome", label: "Metrónomo" },
  { value: "ph:music-note", label: "Nota musical" },
  { value: "ph:music-notes", label: "Notas musicales" },
  { value: "ph:music-note-simple", label: "Nota simple" },
  { value: "ph:music-notes-simple", label: "Notas simples" },
  { value: "ph:music-notes-plus", label: "Composición" },
  { value: "ph:speaker-high", label: "Parlante" },
  { value: "ph:speaker-hifi", label: "Equipo de audio" },
  { value: "ph:headphones", label: "Audífonos" },
  { value: "ph:headset", label: "Diadema" },
  { value: "ph:vinyl-record", label: "Disco de vinilo" },
  { value: "ph:disc", label: "Disco" },
  { value: "ph:waveform", label: "Onda de sonido" },
  { value: "ph:equalizer", label: "Ecualizador" },
  { value: "ph:faders", label: "Consola" },
  { value: "ph:radio", label: "Radio" },
  { value: "ph:playlist", label: "Lista de reproducción" },
  { value: "ph:queue", label: "Cola de reproducción" },
  { value: "ph:bell", label: "Campana / Percusión" },
  { value: "ph:graduation-cap", label: "Teoría / Formación" },
  { value: "ph:book-open", label: "Lectura musical" },
  { value: "ph:users-three", label: "Ensamble / Grupo" },
  { value: "ph:hand-heart", label: "Canto / Expresión" },
  { value: "ph:sparkle", label: "Especial" },
  { value: "ph:star", label: "Destacado" },
  { value: "ph:lightning", label: "Intensivo" },
];
